# Generated by Django 5.2.17 on 2026-09-18 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=255)),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated skills, e.g. Python, Django, SQL",
                        max_length=500,
                    ),
                ),
                ("education", models.TextField(blank=True)),
                ("work_experience", models.TextField(blank=True)),
                (
                    "links",
                    models.TextField(
                        blank=True,
                        help_text="One link per line, e.g. LinkedIn, GitHub, portfolio",
                    ),
                ),
                ("show_skills", models.BooleanField(default=True)),
                ("show_education", models.BooleanField(default=True)),
                ("show_work_experience", models.BooleanField(default=True)),
                ("show_links", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobseeker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
