# Generated by Django 5.2.17 on 2026-10-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_jobseekerprofile_location_jobseekerprofile_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="commute_radius_miles",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="home_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="home_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
