# Generated by Django 5.0 on 2026-10-08 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobseekerprofile_commute_radius_miles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCandidateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('projects', models.CharField(blank=True, max_length=500)),
                ('seen_candidate_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidate_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
